server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/registration
    username: tahayasin
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: # <demo@email.com>
    password: # <top_secret>

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000


security:
  jwt:
    token:
      secret-key: secret-key-for-encryption         # application-specific string used to encrypt tokens
      expiration: 600000                            # token valid for 10 minutes


